### ISSUE TITLE
Grey screen after successful login

### ISSUE THREAD

**Issue by schwartzenheimer** [insin/vlc_remote#12]
After updating to 1.10, the phone graphic comes up with the 'connecting'  animation, and then immediately jumps to a blank grey screen. If I can hit the settings gear icon, it verifies connection, but when exiting back to the main screen, it is just blank grey. It appears that there is a problem with the 'display menu only on successful connection' conditional.

**Comment by insin** [comment]
It looks like a grey screen in production is the Grey Screen of Death, indicating an uncaught error, but not crashing the app badly enough for me to get crash info via Google Play 🤔

I've tried all sorts of combinations of the app's initial state, having VLC on/off, changing the password in VLC etc. but I haven't been able to replicate any errors on startup.

I'll add some top level error handling in the next release which should at least let the app display an error message and stack trace when this happens.

**Comment by insin** [comment]
I've just pushed v1.1.2 to the Play Store, hopefully the new error dialog will get us some info.

**Comment by schwartzenheimer** [comment]
Here is the error message:

NoSuchMethodError: The method '/' was called on null.
Receiver: null
Tried calling: /()

#0      _RemoteControlState._volumeSliderValue
(package:vlc_remote/remote_control.dart:492)
#1      _RemoteControlState._footer
(package:vlc_remote/remote_control.dart:772)
#2      _RemoteControlState.build
(package:vlc_remote/remote_control.dart:685)
#3      StatefulElement.build
(package:flutter/src/widgets/framework.dart:4334)
#4      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4223)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
#6      BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2432)
#7      WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:773)
#8      RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:283)
#9      SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1102)
#10     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1041)
#11     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:957)
#12     _rootRun (dart:async/zone.dart:1126)
#13     _CustomZone.run (dart:async/zone.dart:1023)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925)
#15     _invoke (dart:ui/hooks.dart:259)
#16     _drawFrame (dart:ui/hooks.dart:217)


Thanks for trying to fix this.

Steve

**Comment by insin** [comment]
I wish I could replicate this, as that's really weird. It seems that getting initial status from VLC was successful but it either didn't contain a `<volume></volume>` element or had something other than an integer in its `<volume></volume>` element. I bet if I fix this particular issue something else will blow up instead.

I just noticed a recent review on the Google Play Store that someone said they got a grey screen on Linux but it worked for them on Windows (which is the version of VLC I'm developing against)

@schwartzenheimer Which operating system are you running VLC on and what do you get if you open http://localhost:8080/requests/status.xml on the computer VLC is running on?

**Comment by schwartzenheimer** [comment]
Jonny,

I'm running VLC on Manjaro Linux (Arch).  The old (pre-volume control)
version worked fine.  Attempting to connect to
http://localhost:8080/requests/status.xml results in Connection Refused.
Probably my router/vpn settings.  Let me know if you want me to try to
reconfigure it.

Thanks,
Steve

**Comment by insin** [comment]
I've just pushed v1.1.3 to the play store, which will hopefully fix this.

**Comment by schwartzenheimer** [comment]
Great job, works like a champ. Thank you for following up.  I'll update my
review on Play Store...

Steve
